### ISSUE TITLE
Composer autoload error

### ISSUE THREAD

**Issue by sreichel** [aromicon/magento2-deepl#1]
If you install the extension via composer and rum `setup:upgrade`, you'll get an error "Module Aromicon .... is already defined in app/code/Aromican ...

I think that problem is ....

    "extra": {
        "map": [
            [
                "*",
                "Aromicon/Deepl"
            ]
        ]
    }

... that copies all files to app/code.

**Comment by SRaromicon** [comment]
You are right. We will fix this asap. Thank you for your help.
