### ISSUE TITLE
Configuration Tab for "Aromicon" Not Displayed due to Missing Resource ID in acl.xml

### ISSUE THREAD

**Issue by ijozwiak** [aromicon/magento2-deepl#14]
Hello,

While trying to navigate to the configuration settings of the module, I noticed that the configuration tab for "Aromicon" is missing from the path `Store → Settings → Configuration → “Aromicon”`. Upon investigation, it appears the root cause might be that the resource ID specified in the `system.xml` file is not defined in the `acl.xml` file.

**Steps to reproduce:**

Install the module within the Magento engine version 2.4.6-p2

> Navigate to Store → Settings → Configuration

Try to locate the "Aromicon" tab

**Expected result:**

The "Aromicon" tab should be visible under `Store → Settings → Configuration`.

**Actual result:**

The "Aromicon" tab is missing.

**Possible solution:**

Please verify the resource ID in `system.xml` and ensure it is correctly defined in `acl.xml`.

Thanks for your attention to this issue. Looking forward to a resolution.

**Comment by SRaromicon** [comment]
@ijozwiak Thanks for providing this issue. Should be fixed in our latest version 20.0.0.20

**Comment by ijozwiak** [comment]
I saw it, you are really fast, thank you

Best regards
Iwona

śr., 18 paź 2023 o 13:06 Stefan Richter ***@***.***>
napisał(a):
