### ISSUE TITLE
Add support for Arabic and traditional Chinese

### ISSUE THREAD

**Issue by superdav42** [aromicon/magento2-deepl#15]
From [DeepL docs](https://developers.deepl.com/docs/api-reference/languages):
> As of July 2024, Arabic (AR) and traditional Chinese (ZH-HANT) are supported for text translation but are not yet supported for document translation. Therefore, these languages have not yet been added to the /languages endpoint. We will add these languages to the /languages endpoint where appropriate after document translation support is added. 

Please add support for AR and ZH-HANT.

**Comment by SRaromicon** [comment]
Sorry for late response. New Languages has been added and update.
