### ISSUE TITLE
HTML translation going wrong

### ISSUE THREAD

**Issue by tropilex** [aromicon/magento2-deepl#18]
The translation of some html tags are going wrong. If you translate this in a CMS block:

`<a href="{{config path="web/unsecure/base_url"}}info" class="btn hidden lg:flex btn-secondary bg-gray-100">
`

Then it gets translated to this:

`&lt;a href="{{config path="web/unsecure/base_url"}}info" class="btn hidden lg:flex btn-secondary bg-gray-100"&gt;
`

So < is translated to &lt. And also the closing > tag is translated to &gt.

Magento ver. 2.4.7-p3
Plugin: v2.0.0.20

**Comment by SRaromicon** [comment]
Did you set the tag handling configuration to HTML? Sometimes DeepL ist a bit buggy with tag handling.

**Comment by tropilex** [comment]
@SRaromicon Just tried that. Got exactly the same output.

But I have found the problem! If I remove _{{config path="web/unsecure/base_url"}}_ from the url it's working fine.

So I guess the problem is the {{ or the extra " in the url.

**Comment by spankevich** [comment]
Yes, we also encounter problems when we use widgets in curly braces and try to translate them. deepl periodically returns `{{widget}}` as `{widget}}` (with one curly brace), which breaks the widget itself

**Comment by SRaromicon** [comment]
We are aware of this issue, we will try to replace all directives by a placeholder before translation and return them afterwards. Deepl handles code translation pretty badly. This happens also in pure JSON.
