### ISSUE TITLE
Wrong API URL (v1 instead of v2)

### ISSUE THREAD

**Issue by sreichel** [aromicon/magento2-deepl#2]
After I've saved my API key in config section, the page didnt load corrrectly and a this is logged to system.log

    main.CRITICAL: Authorization failed. Please supply a valid auth_key parameter.  

I changed API url in config.xml to `v2` and it seems to work now.

**Comment by SRaromicon** [comment]
Thank you for suppling this issue. Seems that Deepl has updated their API without any notice. We will fix this too.
