### ISSUE TITLE
Typed property Aromicon\Deepl\Model\Client\Deepl::$usage must not be accessed before initialization 

### ISSUE THREAD

**Issue by spankevich** [aromicon/magento2-deepl#21]
Hello!

I updated the extension to the 20.0.0.22 version, but now I have got this error in the configuration of extension when I attached my API key in the Configuration->Aromicon->Deepl Translate->API key

```Error: Typed property Aromicon\Deepl\Model\Client\Deepl::$usage must not be accessed before initialization in /app/btfww5bauchua_stg/vendor/aromicon/module-deepl/Model/Client/Deepl.php:230```

**Comment by SRaromicon** [comment]
@spankevich We are sorry for this issue. Should be fixed in version 2.0.0.23. Maybe we should write some Tests.

**Comment by spankevich** [comment]
It works now, thanks!
