### ISSUE TITLE
translate:category does not work for all categories

### ISSUE THREAD

**Issue by norgeindian** [aromicon/magento2-deepl#6]
When you run 'translate:category --category=all', the categories are collected by `$this->categoryRepository->getList($filter)->getItems()`.
`categoryRepository` is an instance of `\Magento\Catalog\Api\CategoryRepositoryInterface`.
And there is no function `getList()`.

Please be so kind and fix that. Currently, the command is not working at all.

**Comment by SRaromicon** [comment]
We will fix this very soon. But it's not a feature of the version here. It's one of the Pro Features. New version gets released in composer repository.
Seems to be the only Repository without a List function.

**Comment by norgeindian** [comment]
@SRaromicon , thanks a lot for this fast reply. Great news.
Sorry, you're right, did not check that in detail.
Will close this issue, as it is unrelated to the repo. Sorry again for the mistake.

**Comment by SRaromicon** [comment]
@norgeindian Issue has been fixed in newest version. Thanks for reporting this issue.
