### ISSUE TITLE
Default website isn't defined error while running integration tests.

### ISSUE THREAD

**Issue by BorisovskiP** [aromicon/magento2-deepl#9]
While running integration tests, an error was thrown:

 `In WebsiteRepository.php line 159:
  [DomainException]
  The default website isn't defined. Set the website and try again.
`

Looking at the call stack we saw that 
`Aromicon\Deepl\Helper\Config->getTimeout() at /var/www/html/vendor/aromicon/module-deepl/Model/Client/Deepl.php:51`,
`Aromicon\Deepl\Model\Client\Deepl->__construct() at /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121`
are being called. 

Debbuging into `Aromicon\Deepl\Helper\Config->getTimeout()` did not retrieve the value and throws the error mentioned above. A simple solution to this would be to add a Proxy to the respective dependency of the CLI command, as discribed [here](https://github.com/magento/magento2/issues/27864#issuecomment-666261733)

**Comment by SRaromicon** [comment]
HI this issue should be fixed by  from pull request #10  @frank-bokdam. Thanks for helping out.
